// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.buildGitCommand(System.DateTime,System.DateTime,System.String,System.String,System.String)~System.ValueTuple{System.String,System.String,System.String,System.DateTime,System.DateTime}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_AddedProjectFilePaths_DoWork(System.Object,System.ComponentModel.DoWorkEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.asyncTaskIsRunning(System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_AddedProjectFilePaths_ProgressChanged(System.Object,System.ComponentModel.ProgressChangedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_AddedProjectFilePaths_RunWorkerCompleted(System.Object,System.ComponentModel.RunWorkerCompletedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_BuildOutputFile_DoWork(System.Object,System.ComponentModel.DoWorkEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_BuildOutputFile_ProgressChanged(System.Object,System.ComponentModel.ProgressChangedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_BuildOutputFile_RunWorkerCompleted(System.Object,System.ComponentModel.RunWorkerCompletedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_RunGitCommand_DoWork(System.Object,System.ComponentModel.DoWorkEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_RunGitCommand_ProgressChanged(System.Object,System.ComponentModel.ProgressChangedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_RunGitCommand_RunWorkerCompleted(System.Object,System.ComponentModel.RunWorkerCompletedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_UploadToDrive_DoWork(System.Object,System.ComponentModel.DoWorkEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_UploadToDrive_ProgressChanged(System.Object,System.ComponentModel.ProgressChangedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.bgw_UploadToDrive_RunWorkerCompleted(System.Object,System.ComponentModel.RunWorkerCompletedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.btnAddProjectFilePath_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.btnAddProjectFilePath_Click_Validate")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.btnGenerate_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.btnRemoveSelected_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.btnSearchProjectFilePath_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.buildGitCommand(System.DateTime,System.DateTime,System.String,System.String,System.String)~System.ValueTuple{System.String,System.String,System.String,System.DateTime,System.DateTime}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.buildOutputFile(System.Collections.Generic.IEnumerable{System.String},System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.buildOutputFileName(System.String,System.String,System.String,System.Int32,System.Int32,System.String)~System.ValueTuple{System.String,System.String}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.chkTryToUpload_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.dtpDateFrom_ValueChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.gb_CloudSettings_Validate")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.getExecutionType~ZartisLogs.ExecutionType")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.getMonthsBetween(System.DateTime,System.DateTime)~System.Collections.Generic.IEnumerable{System.ValueTuple{System.Int32,System.Int32}}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.getProjectsByExtensions(System.Collections.Generic.IEnumerable{System.ValueTuple{System.String,System.String,System.String}},System.String,System.String)~System.Collections.Generic.IEnumerable{System.ValueTuple{System.String,System.String,System.String}}")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.initializeConfiguration")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.rb_DateRange_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.rb_DateUpToNow_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.rb_GroupByProjectAndMonth_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.rb_SingleFileByMonthAndYear_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.rb_SingleFileByProject_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.rb_SingleMonth_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.setDefaultConfiguration")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.setInitialValues")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.setLatestsValues")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.setStep2DateSetVisibility(System.Boolean,System.Boolean,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.setStep2DateSetVisibility_Validate")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.setStep6GeneratedFileNamePattern(System.Boolean,System.Boolean,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.setStep6GeneratedFileNamePattern_Validate")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:ZartisLogs.Main.updateAppSettings")]
